# Generated by Django 6.0.6 on 2026-06-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The input text that was analysed.')),
                ('polarity', models.FloatField(help_text='Polarity score from -1.0 (most negative) to +1.0 (most positive).')),
                ('subjectivity', models.FloatField(help_text='Subjectivity score from 0.0 (objective) to 1.0 (subjective).')),
                ('classification', models.CharField(choices=[('very_positive', 'Very Positive'), ('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('very_negative', 'Very Negative')], help_text='Human-readable sentiment classification.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
